// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cftemfwrgacaymhjjgmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmdGVtZndyZ2FjYXltaGpqZ214Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDYyODgsImV4cCI6MjA3MjMyMjI4OH0.L9FRT-jdLVeMGd57ZpWxFqpInMC0SfB8mNtN1G_LVqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});